// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCodeGenerator is an autogenerated mock type for the CodeGenerator type
type MockCodeGenerator struct {
	mock.Mock
}

type MockCodeGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCodeGenerator) EXPECT() *MockCodeGenerator_Expecter {
	return &MockCodeGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: id
func (_m *MockCodeGenerator) Generate(id uint) (string, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (string, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCodeGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockCodeGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - id uint
func (_e *MockCodeGenerator_Expecter) Generate(id interface{}) *MockCodeGenerator_Generate_Call {
	return &MockCodeGenerator_Generate_Call{Call: _e.mock.On("Generate", id)}
}

func (_c *MockCodeGenerator_Generate_Call) Run(run func(id uint)) *MockCodeGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockCodeGenerator_Generate_Call) Return(_a0 string, _a1 error) *MockCodeGenerator_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCodeGenerator_Generate_Call) RunAndReturn(run func(uint) (string, error)) *MockCodeGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCodeGenerator creates a new instance of MockCodeGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCodeGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCodeGenerator {
	mock := &MockCodeGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
