// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: shortCode
func (_m *MockCache) Get(shortCode string) (string, bool) {
	ret := _m.Called(shortCode)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(shortCode)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(shortCode)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - shortCode string
func (_e *MockCache_Expecter) Get(shortCode interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", shortCode)}
}

func (_c *MockCache_Get_Call) Run(run func(shortCode string)) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(_a0 string, _a1 bool) *MockCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(string) (string, bool)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: shortCode, originalURL
func (_m *MockCache) Set(shortCode string, originalURL string) {
	_m.Called(shortCode, originalURL)
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - shortCode string
//   - originalURL string
func (_e *MockCache_Expecter) Set(shortCode interface{}, originalURL interface{}) *MockCache_Set_Call {
	return &MockCache_Set_Call{Call: _e.mock.On("Set", shortCode, originalURL)}
}

func (_c *MockCache_Set_Call) Run(run func(shortCode string, originalURL string)) *MockCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCache_Set_Call) Return() *MockCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCache_Set_Call) RunAndReturn(run func(string, string)) *MockCache_Set_Call {
	_c.Run(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
