// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "urlshortener/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, id, shortCode, originalURL
func (_m *MockRepository) Create(ctx context.Context, id uint, shortCode string, originalURL string) error {
	ret := _m.Called(ctx, id, shortCode, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string) error); ok {
		r0 = rf(ctx, id, shortCode, originalURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - shortCode string
//   - originalURL string
func (_e *MockRepository_Expecter) Create(ctx interface{}, id interface{}, shortCode interface{}, originalURL interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, id, shortCode, originalURL)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, id uint, shortCode string, originalURL string)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, uint, string, string) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, urls
func (_m *MockRepository) CreateBatch(ctx context.Context, urls []repository.URLRow) error {
	ret := _m.Called(ctx, urls)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.URLRow) error); ok {
		r0 = rf(ctx, urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockRepository_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - urls []repository.URLRow
func (_e *MockRepository_Expecter) CreateBatch(ctx interface{}, urls interface{}) *MockRepository_CreateBatch_Call {
	return &MockRepository_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, urls)}
}

func (_c *MockRepository_CreateBatch_Call) Run(run func(ctx context.Context, urls []repository.URLRow)) *MockRepository_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]repository.URLRow))
	})
	return _c
}

func (_c *MockRepository_CreateBatch_Call) Return(_a0 error) *MockRepository_CreateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateBatch_Call) RunAndReturn(run func(context.Context, []repository.URLRow) error) *MockRepository_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// FindByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *MockRepository) FindByShortCode(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for FindByShortCode")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByShortCode'
type MockRepository_FindByShortCode_Call struct {
	*mock.Call
}

// FindByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockRepository_Expecter) FindByShortCode(ctx interface{}, shortCode interface{}) *MockRepository_FindByShortCode_Call {
	return &MockRepository_FindByShortCode_Call{Call: _e.mock.On("FindByShortCode", ctx, shortCode)}
}

func (_c *MockRepository_FindByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockRepository_FindByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindByShortCode_Call) Return(_a0 string, _a1 error) *MockRepository_FindByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindByShortCode_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRepository_FindByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NextID provides a mock function with given fields: ctx
func (_m *MockRepository) NextID(ctx context.Context) (uint, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockRepository_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) NextID(ctx interface{}) *MockRepository_NextID_Call {
	return &MockRepository_NextID_Call{Call: _e.mock.On("NextID", ctx)}
}

func (_c *MockRepository_NextID_Call) Run(run func(ctx context.Context)) *MockRepository_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_NextID_Call) Return(_a0 uint, _a1 error) *MockRepository_NextID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_NextID_Call) RunAndReturn(run func(context.Context) (uint, error)) *MockRepository_NextID_Call {
	_c.Call.Return(run)
	return _c
}

// NextIDs provides a mock function with given fields: ctx, count
func (_m *MockRepository) NextIDs(ctx context.Context, count int) ([]uint, error) {
	ret := _m.Called(ctx, count)

	if len(ret) == 0 {
		panic("no return value specified for NextIDs")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]uint, error)); ok {
		return rf(ctx, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []uint); ok {
		r0 = rf(ctx, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_NextIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextIDs'
type MockRepository_NextIDs_Call struct {
	*mock.Call
}

// NextIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - count int
func (_e *MockRepository_Expecter) NextIDs(ctx interface{}, count interface{}) *MockRepository_NextIDs_Call {
	return &MockRepository_NextIDs_Call{Call: _e.mock.On("NextIDs", ctx, count)}
}

func (_c *MockRepository_NextIDs_Call) Run(run func(ctx context.Context, count int)) *MockRepository_NextIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_NextIDs_Call) Return(_a0 []uint, _a1 error) *MockRepository_NextIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_NextIDs_Call) RunAndReturn(run func(context.Context, int) ([]uint, error)) *MockRepository_NextIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
