#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${GRAFANA_DB_USER:-grafana} WITH PASSWORD '${GRAFANA_DB_PASSWORD:-grafana_readonly}';
    GRANT CONNECT ON DATABASE $POSTGRES_DB TO ${GRAFANA_DB_USER:-grafana};
    GRANT USAGE ON SCHEMA public TO ${GRAFANA_DB_USER:-grafana};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${GRAFANA_DB_USER:-grafana};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${GRAFANA_DB_USER:-grafana};
EOSQL
