// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	metrics "urlshortener/internal/metrics"

	mock "github.com/stretchr/testify/mock"
)

// MockHTTPRecorder is an autogenerated mock type for the HTTPRecorder type
type MockHTTPRecorder struct {
	mock.Mock
}

type MockHTTPRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPRecorder) EXPECT() *MockHTTPRecorder_Expecter {
	return &MockHTTPRecorder_Expecter{mock: &_m.Mock}
}

// RecordHTTP provides a mock function with given fields: m
func (_m *MockHTTPRecorder) RecordHTTP(m metrics.HTTPMetric) {
	_m.Called(m)
}

// MockHTTPRecorder_RecordHTTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordHTTP'
type MockHTTPRecorder_RecordHTTP_Call struct {
	*mock.Call
}

// RecordHTTP is a helper method to define mock.On call
//   - m metrics.HTTPMetric
func (_e *MockHTTPRecorder_Expecter) RecordHTTP(m interface{}) *MockHTTPRecorder_RecordHTTP_Call {
	return &MockHTTPRecorder_RecordHTTP_Call{Call: _e.mock.On("RecordHTTP", m)}
}

func (_c *MockHTTPRecorder_RecordHTTP_Call) Run(run func(m metrics.HTTPMetric)) *MockHTTPRecorder_RecordHTTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metrics.HTTPMetric))
	})
	return _c
}

func (_c *MockHTTPRecorder_RecordHTTP_Call) Return() *MockHTTPRecorder_RecordHTTP_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHTTPRecorder_RecordHTTP_Call) RunAndReturn(run func(metrics.HTTPMetric)) *MockHTTPRecorder_RecordHTTP_Call {
	_c.Run(run)
	return _c
}

// NewMockHTTPRecorder creates a new instance of MockHTTPRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPRecorder {
	mock := &MockHTTPRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
