// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockURLValidator is an autogenerated mock type for the URLValidator type
type MockURLValidator struct {
	mock.Mock
}

type MockURLValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLValidator) EXPECT() *MockURLValidator_Expecter {
	return &MockURLValidator_Expecter{mock: &_m.Mock}
}

// ValidateBatch provides a mock function with given fields: urls
func (_m *MockURLValidator) ValidateBatch(urls []string) error {
	ret := _m.Called(urls)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLValidator_ValidateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBatch'
type MockURLValidator_ValidateBatch_Call struct {
	*mock.Call
}

// ValidateBatch is a helper method to define mock.On call
//   - urls []string
func (_e *MockURLValidator_Expecter) ValidateBatch(urls interface{}) *MockURLValidator_ValidateBatch_Call {
	return &MockURLValidator_ValidateBatch_Call{Call: _e.mock.On("ValidateBatch", urls)}
}

func (_c *MockURLValidator_ValidateBatch_Call) Run(run func(urls []string)) *MockURLValidator_ValidateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *MockURLValidator_ValidateBatch_Call) Return(_a0 error) *MockURLValidator_ValidateBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLValidator_ValidateBatch_Call) RunAndReturn(run func([]string) error) *MockURLValidator_ValidateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateURL provides a mock function with given fields: url
func (_m *MockURLValidator) ValidateURL(url string) error {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for ValidateURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLValidator_ValidateURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateURL'
type MockURLValidator_ValidateURL_Call struct {
	*mock.Call
}

// ValidateURL is a helper method to define mock.On call
//   - url string
func (_e *MockURLValidator_Expecter) ValidateURL(url interface{}) *MockURLValidator_ValidateURL_Call {
	return &MockURLValidator_ValidateURL_Call{Call: _e.mock.On("ValidateURL", url)}
}

func (_c *MockURLValidator_ValidateURL_Call) Run(run func(url string)) *MockURLValidator_ValidateURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLValidator_ValidateURL_Call) Return(_a0 error) *MockURLValidator_ValidateURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLValidator_ValidateURL_Call) RunAndReturn(run func(string) error) *MockURLValidator_ValidateURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLValidator creates a new instance of MockURLValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLValidator {
	mock := &MockURLValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
