// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "urlshortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockURLService is an autogenerated mock type for the URLService type
type MockURLService struct {
	mock.Mock
}

type MockURLService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLService) EXPECT() *MockURLService_Expecter {
	return &MockURLService_Expecter{mock: &_m.Mock}
}

// CreateShortURL provides a mock function with given fields: ctx, originalURL
func (_m *MockURLService) CreateShortURL(ctx context.Context, originalURL string) (*domain.CreateURLResponse, error) {
	ret := _m.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 *domain.CreateURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.CreateURLResponse, error)); ok {
		return rf(ctx, originalURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.CreateURLResponse); ok {
		r0 = rf(ctx, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_CreateShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURL'
type MockURLService_CreateShortURL_Call struct {
	*mock.Call
}

// CreateShortURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *MockURLService_Expecter) CreateShortURL(ctx interface{}, originalURL interface{}) *MockURLService_CreateShortURL_Call {
	return &MockURLService_CreateShortURL_Call{Call: _e.mock.On("CreateShortURL", ctx, originalURL)}
}

func (_c *MockURLService_CreateShortURL_Call) Run(run func(ctx context.Context, originalURL string)) *MockURLService_CreateShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_CreateShortURL_Call) Return(_a0 *domain.CreateURLResponse, _a1 error) *MockURLService_CreateShortURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_CreateShortURL_Call) RunAndReturn(run func(context.Context, string) (*domain.CreateURLResponse, error)) *MockURLService_CreateShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShortURLBatch provides a mock function with given fields: ctx, originalURLs
func (_m *MockURLService) CreateShortURLBatch(ctx context.Context, originalURLs []string) ([]domain.CreateURLResponse, error) {
	ret := _m.Called(ctx, originalURLs)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURLBatch")
	}

	var r0 []domain.CreateURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]domain.CreateURLResponse, error)); ok {
		return rf(ctx, originalURLs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []domain.CreateURLResponse); ok {
		r0 = rf(ctx, originalURLs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CreateURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, originalURLs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_CreateShortURLBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortURLBatch'
type MockURLService_CreateShortURLBatch_Call struct {
	*mock.Call
}

// CreateShortURLBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURLs []string
func (_e *MockURLService_Expecter) CreateShortURLBatch(ctx interface{}, originalURLs interface{}) *MockURLService_CreateShortURLBatch_Call {
	return &MockURLService_CreateShortURLBatch_Call{Call: _e.mock.On("CreateShortURLBatch", ctx, originalURLs)}
}

func (_c *MockURLService_CreateShortURLBatch_Call) Run(run func(ctx context.Context, originalURLs []string)) *MockURLService_CreateShortURLBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockURLService_CreateShortURLBatch_Call) Return(_a0 []domain.CreateURLResponse, _a1 error) *MockURLService_CreateShortURLBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_CreateShortURLBatch_Call) RunAndReturn(run func(context.Context, []string) ([]domain.CreateURLResponse, error)) *MockURLService_CreateShortURLBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalURL provides a mock function with given fields: ctx, shortCode
func (_m *MockURLService) GetOriginalURL(ctx context.Context, shortCode string) (string, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLService_GetOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalURL'
type MockURLService_GetOriginalURL_Call struct {
	*mock.Call
}

// GetOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockURLService_Expecter) GetOriginalURL(ctx interface{}, shortCode interface{}) *MockURLService_GetOriginalURL_Call {
	return &MockURLService_GetOriginalURL_Call{Call: _e.mock.On("GetOriginalURL", ctx, shortCode)}
}

func (_c *MockURLService_GetOriginalURL_Call) Run(run func(ctx context.Context, shortCode string)) *MockURLService_GetOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockURLService_GetOriginalURL_Call) Return(_a0 string, _a1 error) *MockURLService_GetOriginalURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLService_GetOriginalURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockURLService_GetOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLService creates a new instance of MockURLService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLService {
	mock := &MockURLService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
