// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockBusinessRecorder is an autogenerated mock type for the BusinessRecorder type
type MockBusinessRecorder struct {
	mock.Mock
}

type MockBusinessRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBusinessRecorder) EXPECT() *MockBusinessRecorder_Expecter {
	return &MockBusinessRecorder_Expecter{mock: &_m.Mock}
}

// RecordBusiness provides a mock function with given fields: name, value, labels
func (_m *MockBusinessRecorder) RecordBusiness(name string, value float64, labels map[string]string) {
	_m.Called(name, value, labels)
}

// MockBusinessRecorder_RecordBusiness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordBusiness'
type MockBusinessRecorder_RecordBusiness_Call struct {
	*mock.Call
}

// RecordBusiness is a helper method to define mock.On call
//   - name string
//   - value float64
//   - labels map[string]string
func (_e *MockBusinessRecorder_Expecter) RecordBusiness(name interface{}, value interface{}, labels interface{}) *MockBusinessRecorder_RecordBusiness_Call {
	return &MockBusinessRecorder_RecordBusiness_Call{Call: _e.mock.On("RecordBusiness", name, value, labels)}
}

func (_c *MockBusinessRecorder_RecordBusiness_Call) Run(run func(name string, value float64, labels map[string]string)) *MockBusinessRecorder_RecordBusiness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(float64), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockBusinessRecorder_RecordBusiness_Call) Return() *MockBusinessRecorder_RecordBusiness_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBusinessRecorder_RecordBusiness_Call) RunAndReturn(run func(string, float64, map[string]string)) *MockBusinessRecorder_RecordBusiness_Call {
	_c.Run(run)
	return _c
}

// NewMockBusinessRecorder creates a new instance of MockBusinessRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBusinessRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBusinessRecorder {
	mock := &MockBusinessRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
